Fix for empty names and empty times
Glartek/senml-js pull request #4
Opened 2023-03-01 18:59 UTC by gebsl

Hi @marcotuna,

first of all thanks for your work and this great package!

I've tried to normalize an example from the RFC8428, namely [example 5.1.3](https://datatracker.ietf.org/doc/html/rfc8428#section-5.1.3) and have come across the issue that the library did not handle empty names and empty timestamps well, when there is only a base name and a base time given.

This PR should fix both issues. I've also included a test for this very example.
I was just thinking whether it makes sense to include the whole example 5.1.3 into the test-case. What is your opinion on this?

Best regards,
Gabriel

2023-03-01 20:36 UTC, marcotuna commented
Hi @gebsl,

Thank you so much for your contribution and for pointing out the issue with empty names and timestamps. I appreciate your effort in fixing it and including a test case for it. Your contribution will definitely help improve the functionality of the package.

Regarding your question about including the whole example 5.1.3 into the test-case, I think it's a great idea. Including the whole example would ensure that the package is able to handle all aspects and that it is fully compliant with the RFC8428. 

I will merge your changes into the main branch shortly. Once again, thank you for your contribution!

2023-03-01 21:14 UTC, marcotuna requested changes

2023-03-01 21:14 UTC, marcotuna commented on src/index.ts
> +    r.n = bname + (r.n ?? '');
To ensure compatibility with older versions of NodeJS, I suggest replacing the nullish coalescing operator with a ternary operator.

```suggestion
    r.t = (r.t !== undefined && r.t !== null ? r.t : 0) + btime;
    r.n = bname + (r.n !== undefined && r.n !== null ? r.n : '');
```

Feel free to modify the code, as long as the compatibility with older NodeJS versions are kept.

2023-03-02 07:35 UTC, gebsl commented
@marcotuna thanks for pointing this out! I think your approach is quite elegant, so I directly commited it :-)

2023-03-02 21:46 UTC, merged